apiVersion: v1
data:
  jmx-zookeeper-prometheus.yml: |
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
    - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+)><>(\\w+)"
      name: "cp_zookeeper_$2"
    - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+)><>(\\w+)"
      name: "cp_zookeeper_$3"
      labels:
        replicaId: "$2"
    - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(\\w+)"
      name: "cp_zookeeper_$4"
      labels:
        replicaId: "$2"
        memberType: "$3"
    - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+), name3=(\\w+)><>(\\w+)"
      name: "cp_zookeeper_$4_$5"
      labels:
        replicaId: "$2"
        memberType: "$3"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: iz-kafka
    meta.helm.sh/release-namespace: izdev
  creationTimestamp: "2020-08-26T19:01:15Z"
  labels:
    app: cp-zookeeper
    app.kubernetes.io/managed-by: Helm
    chart: cp-zookeeper-0.1.0
    heritage: Helm
    release: iz-kafka
  name: iz-kafka-cp-zookeeper-jmx-configmap
  namespace: izdev
  resourceVersion: "17686"
  selfLink: /api/v1/namespaces/izdev/configmaps/iz-kafka-cp-zookeeper-jmx-configmap
  uid: 22279c19-eb15-44cb-bb26-075431c25370
