apiVersion: v1
data:
  jmx-kafka-connect-prometheus.yml: |
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
    - pattern : "kafka.connect<type=connect-worker-metrics>([^:]+):"
      name: "cp_kafka_connect_connect_worker_metrics_$1"
    - pattern : "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
      name: "cp_kafka_connect_connect_metrics_$1_$2"
    - pattern : "kafka.connect<type=connector-task-metrics, connector=([^:]+), task=([^:]+)><>status: ([^:]+)"
      name: "cp_kafka_connect_connect_connector_metrics"
      value: 1
      labels:
        connector: $1
        task: $2
        status: $3
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: iz-kafka
    meta.helm.sh/release-namespace: izdev
  creationTimestamp: "2020-08-26T19:01:15Z"
  labels:
    app: cp-kafka-connect
    app.kubernetes.io/managed-by: Helm
    chart: cp-kafka-connect-0.1.0
    heritage: Helm
    release: iz-kafka
  name: iz-kafka-cp-kafka-connect-jmx-configmap
  namespace: izdev
  resourceVersion: "17690"
  selfLink: /api/v1/namespaces/izdev/configmaps/iz-kafka-cp-kafka-connect-jmx-configmap
  uid: 0d4b55ad-7b96-4862-b1d4-ac3b94b9f67c
